### ISSUE TITLE
As a developer, I want to make wireframes for my webapplication, so that I have a better understanding of the elements on my pages.

### ISSUE THREAD

**Issue by TylerRijk** [Team-Programmeer-Profeten/ShareDiMobiHub#1]
# Description

Create wireframes for the web application to visualize the layout and elements on each page.

# Definition of Ready

- [ ] Clear understanding of the needs.
- [ ] Requirements for the web application are finalized.

# Definition of Done

- [ ] Wireframes are created for all pages of the web application.
- [ ] Each wireframe represents the layout and elements on the corresponding page.
- [ ] Wireframes are reviewed and approved by stakeholders.
- [ ] Any necessary revisions based on feedback are implemented.

# Tasks

- [ ] #2
