### ISSUE TITLE
As a user, I want to securely login, so that I can ultimately see the report generation page.

### ISSUE THREAD

**Issue by TylerRijk** [Team-Programmeer-Profeten/ShareDiMobiHub#13]
# Description

Make a login-page that checks the login details from an employee of a municipality.

# Definition of Ready

- [ ] Know what type of authorization and security we would like to use

# Definition of Done

- [ ] The page should include fields for entering a username and password.
- [ ] Logos of stakeholders should be integrated into the login page to provide visual branding and recognition.
- [ ] Upon login, the system should verify the user's associated municipality and prepare their data for display on the following page.
- [ ] On the right of the page, there will be an example report to show.

# Tasks

- [ ] #14
- [ ] #16
- [ ] #18
- [ ] #19
- [ ] #20
- [ ] #21
