### ISSUE TITLE
As a user, I want to see all the options, so that I can select the ones that I want in my report.

### ISSUE THREAD

**Issue by TylerRijk** [Team-Programmeer-Profeten/ShareDiMobiHub#3]
# Description

When a certain user from a municipality has landed on the main page, he or she can see all the options that he or she wants to select to have in their report. Focus on the functionality first.

# Definition of Ready

- [ ] #1 
- [ ] Know which options are available
- [ ] Know how Vue.js works
- [ ] Know how TypeScript works
- [ ] Know how Tailwindcss works

# Definition of Done

- [ ] On the page are the following options:

-  Onderwerpen: "Aantal voertuigen", "Afstand afgelegd", "Verhuringen", "Zone bezetting"
-  Wijk, buurt en monitoringszone: (Alles binnen een gemeente, gebruik gestuurde json)
-  Tijdschaal: "Uur-data", "Dag-data", "Maand-data", Jaar-data"
-  Periode: 2 datums (datepicker)

- [ ] A button that says "Genereer rapport"
- [ ] An additional information hover icon / button with an explanation about the option
- [ ] When clicked on the button to generate a report, all the options in json format

# Tasks

- [ ] Make the layout of the page with all the options
- [ ] Make an additional information hover icon / button for every option
- [ ] Make a button that makes a json from all the options
